//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KojVenStatistic.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeal
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> DiseaseId { get; set; }
        public System.DateTime DateOfRequest { get; set; }
        public int AppealTypeId { get; set; }
        public Nullable<System.DateTime> DateOfFinish { get; set; }
        public string Comment { get; set; }
    
        public virtual AppealType AppealType { get; set; }
        public virtual Client Client { get; set; }
        public virtual Disease Disease { get; set; }
        public virtual User User { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
