//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KojVenStatistic.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeal
    {
        public Appeal()
        {
            this.Recipe = new HashSet<Recipe>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int UserId { get; set; }
        public int DiseaseId { get; set; }
        public System.DateTime DateOfRequest { get; set; }
        public string Comment { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Disease Disease { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Recipe> Recipe { get; set; }
    }
}
