//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KojVenStatistic.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Appeal = new HashSet<Appeal>();
        }
    
        public int Id { get; set; }
        public string Snils { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PassportNumber { get; set; }
        public string PassportSeria { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Telephone { get; set; }
        public string MedPolis { get; set; }
        public int GenderId { get; set; }
    
        public virtual ICollection<Appeal> Appeal { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
