//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KojVenStatistic.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Appeal = new HashSet<Appeal>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NumberPassport { get; set; }
        public string Adress { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Snils { get; set; }
        public string MedPolis { get; set; }
        public int GenderId { get; set; }
    
        public virtual ICollection<Appeal> Appeal { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
