//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KojVenStatistic.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disease
    {
        public Disease()
        {
            this.Appeal = new HashSet<Appeal>();
            this.Medicament = new HashSet<Medicament>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeDiseaseId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Appeal> Appeal { get; set; }
        public virtual TypeDisease TypeDisease { get; set; }
        public virtual ICollection<Medicament> Medicament { get; set; }
    }
}
