//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KojVenStatistic.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicamentOfRecipe
    {
        public int MedicamentId { get; set; }
        public int RecipeId { get; set; }
        public int AmountPerDay { get; set; }
    
        public virtual Medicament Medicament { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
