//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KojVenStatistic.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicamentOfRecipe
    {
        public int MedicamentId { get; set; }
        public int RecipeId { get; set; }
        public int AmountPerDay { get; set; }
    
        public virtual Medicament Medicament { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
