//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KojVenStatistic.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KojVenStatisticEntities : DbContext
    {
        public KojVenStatisticEntities()
            : base("name=KojVenStatisticEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Appeal> Appeal { get; set; }
        public DbSet<AppealType> AppealType { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Disease> Disease { get; set; }
        public DbSet<Gender> Gender { get; set; }
        public DbSet<Medicament> Medicament { get; set; }
        public DbSet<MedicamentOfRecipe> MedicamentOfRecipe { get; set; }
        public DbSet<Post> Post { get; set; }
        public DbSet<Recipe> Recipe { get; set; }
        public DbSet<TypeDisease> TypeDisease { get; set; }
        public DbSet<User> User { get; set; }
    }
}
