//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KojVenStatistic.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string PostName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<User> User { get; set; }
    }
}
