//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KojVenStatistic.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.MedicamentOfRecipe = new HashSet<MedicamentOfRecipe>();
        }
    
        public int Id { get; set; }
        public int AppealId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Appeal Appeal { get; set; }
        public virtual ICollection<MedicamentOfRecipe> MedicamentOfRecipe { get; set; }
    }
}
