//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KojVenStatistic.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int Id { get; set; }
        public int AppealId { get; set; }
        public System.DateTime Date { get; set; }
        public int MedicamentId { get; set; }
    
        public virtual Appeal Appeal { get; set; }
        public virtual Medicament Medicament { get; set; }
    }
}
